### ISSUE TITLE
Add texts for the tutorials

### ISSUE THREAD

**Issue by estan** [mbroadst/qamqp#14]
The tutorials are currently just code samples. It would be great if there was some explaining text for each tutorial, perhaps as GitHub wiki pages?

**Comment by mbroadst** [comment]
@estan these tutorials are ports of the java tutorials found [here](http://www.rabbitmq.com/getstarted.html). That page has pretty good text descriptions for each of the tutorials

**Comment by estan** [comment]
Ah. Fair enough.
