### ISSUE TITLE
debian packages

### ISSUE THREAD

**Issue by qmor** [mbroadst/qamqp#15]
Are you planning to put qamqp library into debian repo?

**Comment by mbroadst** [comment]
@qmor I don't currently have a need for that, but I would gladly accept a PR for packaging rules for debian if you'd like to help maintain that

**Comment by qmor** [comment]
Okay. I could try to put it into debian testing repository. I don't sure that it will be easy, because of some repo rules.

**Comment by mbroadst** [comment]
please let me know of any changes we need to make here to help you

**Comment by AdamMajer** [comment]
On Tue, Feb 17, 2015 at 09:03:06AM -0800, qmor wrote:
>    Okay. I could try to put it into debian testing repository. I don't sure
>    that it will be easy, because of some repo rules.

Debian Jessie is frozen. There is no new packages going in for over 2
months now. Also, all uploads go to Sid (unstable) - you (almost)
never upload to testing.

This bit of Debian trivia was brought to you by,
- Adam

**Comment by qmor** [comment]
>Debian Jessie is frozen. There is no new packages going in for over 2
>months now. Also, all uploads go to Sid (unstable) - you (almost)
>never upload to testing.

>This bit of Debian trivia was brought to you by,
>- Adam
Thanks

**Comment by sjlongland** [comment]
I had an initial stab at this this morning.  Only tested on Debian Wheezy i386 at present.

https://github.com/mbroadst/qamqp/pull/22
