### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by apomykal** [mbroadst/qamqp#17]
I  noticed the license changed at some point from MIT to the GNU GPL and was wondering about the history behind this.   Thx.

**Comment by mbroadst** [comment]
@apomykal because I wanted to make sure that the project continues to grow and thrive in the open source world. MIT has no provision that modifications to this source base are ever contributed back, while the LGPL does

**Comment by AdamMajer** [comment]
On Mon, Mar 02, 2015 at 01:47:28PM -0800, Andrew Pomykal wrote:
>    I noticed the license changed at some point from MIT to the GNU GPL and
>    was wondering about the history behind this. Thx.

There are whole modules of Qt licensed under LGPL whether you buy
commercial license or not, so this should not be an issue. For
example, Qt Webkit module is LGPL.

QAMQP may need an exception similar to Qt's LGPL exception for
inline functions.

- Adam

**Comment by apomykal** [comment]
Thanks, appreciate the timely response.

**Comment by mbroadst** [comment]
@apomykal no problem, let us know if you have any issues but I think you'll find the LGPL, while lacking in certain respects, generally promotes free growth in public and private sectors for open source projects. Thanks for your interest in the project
