### ISSUE TITLE
waitForBytesWritten(1000) causing "Network operation timeout"

### ISSUE THREAD

**Issue by redkite1** [mbroadst/qamqp#19]
waitForBytesWritten(1000) on line:
https://github.com/mbroadst/qamqp/blob/master/src/qamqpframe.cpp#L61

Why are you using a so small timeout? (The default is 30000 ;-))

Well, I suppose that my application is really busy. But anyway, I'm trying to upgrading my app from fuCtor/QAMQP and I was wondering what was your reason for adding this?
As soon as I increase it, it's ok.
But as soon as I reduce it, I'm having problem more often.
And I checked with wireshark for the time between my exchange declaration and the error. It was always matching the time I set on this line.

(I know, I could simply add an option for that in a fork, but I'm curious :-))

**Comment by mbroadst** [comment]
honestly I couldn't tell you at this point :smile:  I imagine it just sped up testing at the time, if you put together a PR together I'll accept it. Ideally, it'd be nice to make it a configurable value set on e.g. QAmqpClient?

**Comment by redkite1** [comment]
Yes, of course, I was going to add something like:
`void QAmqpClient::setWriteTimeout(int msecs);`
`int QAmqpClient::getWriteTimeout() const;`

**Comment by redkite1** [comment]
Maybe writeTimeout instead of getWriteTimeout if I want to match your code.

**Comment by mbroadst** [comment]
yeah, I try to stick to Qt style guidelines. That sounds good to me, unless there's a more descriptive name (not sure I can think of one off the top of my head).

**Comment by redkite1** [comment]
setFrameWriteTiemout ?

**Comment by mbroadst** [comment]
I think setWriteTimeout is okay for now, if it conflicts in the future we can add setFrameWriteTimeout and not break BC, but just change the meaning

**Comment by redkite1** [comment]
ok, will do it on monday.
Have a good week-end and thanks for your fast answers!

**Comment by mbroadst** [comment]
@redkite1 np, thanks for the help! have a great weekend

**Comment by redkite1** [comment]
Hello Matt,

I need the writeTimeout inside QDataStream &operator<<(...) in qamqpframe_p.h which have no idea of the client used, and in multiple place where QAmqpFrame is used, there is no client available.

Where do you expect me to put this parameter?
The easiest one would be a static setter and getter on QAmqpFrame, but I would need a mutex for protecting the setter ><.

**Comment by redkite1** [comment]
QAmqpFrame is not in the INSTALL_HEADERS :-/

**Comment by mbroadst** [comment]
@redkite1 QAmqpFrame isn't exported that's right, but you can still make it a static method on QAmqpClient that internally accesses a static variable on QAmqpFrame or something? Keeping the property on QAmqpClient makes most sense to me, as its where you would expect to find it.

**Comment by droidsyer** [comment]
Hello Matt,
I have a problem with method waitForBytesWritten.
Sometimes my application is locked when is called this method (timeout expired). 
Although I try to modify writeTimeout (i.e. -1; 5 or 30), when timeout expires, rabbitMQ server disconnects me.

But if I try to delete it, it works!
