### ISSUE TITLE
ChannelNumber doesn't work

### ISSUE THREAD

**Issue by droidsyer** [mbroadst/qamqp#42]
Exchanges and Queues are build with default parameter `channelNumber = -1` , so it is incremented each new instance of it.
If I try to set a fixed channelNumber, i.e. 1, this setting doesn't work as well:

No connection is established!

**Comment by mbroadst** [comment]
@droidsyer hey thanks for the bug report, I was away on vacation. The last commit should fix your issue, I've included a test for it
