### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by kdawg14** [mbroadst/qamqp#43]
I'm a little confused by what license this is actually released under.  Your LICENSE file has the following:

> > QAMQP is Copyright (C) 2014-2015 Matt Broadstone
> 
>  You may use, distribute and copy QJsonRpc under the terms of
>  GNU Library General Public License version 2, which is displayed below.

Should that QJsonRpc say QAMQP, or is there a QJsonRpc component that we could use if we wanted to that's GPL'ed?  Also, your source files have:

> [...] you can redistribute it and/or
>  * modify it under the terms of the GNU Lesser General Public
>  * License as published by the Free Software Foundation; either
>  * version 2.1 of the License, or (at your option) any later version.

So it's a bit unclear as to what license applies here.

Thanks!

**Comment by mbroadst** [comment]
@kdawg14 aha! oops, yeah sorry this is a failed case of copy pasta indeed. When setting up the "bones" of the project during refactoring I copied a lot of files over from another project I wrote: qjsonrpc. I'll sort that out immediately, but the project is indeed licensed under LGPLv2

**Comment by mbroadst** [comment]
fixed in 1088e6f6bf2cecfd1d8e7fa26cbe8bdd3f42aef3

**Comment by kdawg14** [comment]
Great, thanks for clarifying!
