### ISSUE TITLE
Tagged Versions

### ISSUE THREAD

**Issue by WarheadsSE** [mbroadst/qamqp#44]
Could the community get some tagged revisions? It would be far cleaner if we could do packaging based on github tarball downloads or git tags vs revision locks.

**Comment by mbroadst** [comment]
Tags 0.4.0 (for when the actual bump happened) and 0.5.0 (for current state of code) pushed.

The project is no longer in active development but rather maintenance mode as I haven't needed it for some time. Would be great if you guys wanted to be involved in some of that maintenance?

**Comment by WarheadsSE** [comment]
TY sir. We'll look into the allocation of resources.
