### ISSUE TITLE
Hostname resolution

### ISSUE THREAD

**Issue by MangoCats** [mbroadst/qamqp#56]
I am having very good performance and results using raw IP addresses (10.10.10.100 192.168.1.100 etc.) but when I try to use a hostname instead, I cannot connect to the rabbit server (connectToHost myhostname:5672 -> socketError 2).

On the same machine, ping of myhostname works correctly... these are mostly ubuntu and raspbian machines I'm testing on, similar results on both.

Any ideas?

Thanks,

**Comment by mbroadst** [comment]
@MangoCats sounds like you have resolution issues on your system that are out of scope for this library. Internally QAMQP is using [QAbstractSocket::connectToHost](https://code.woboq.org/qt5/qtbase/src/network/socket/qabstractsocket.h.html#_ZN15QAbstractSocket13connectToHostERK12QHostAddresst6QFlagsIN9QIODevice12OpenModeFlagEE) which internally uses the socket engine to resolve hostnames.
