### ISSUE TITLE
Exchange list

### ISSUE THREAD

**Issue by KonstantinZvyagin** [mbroadst/qamqp#61]
Is it possible to get an actual list of exchanges  from server ?
I know that i can do it throw curl and http api. But more simple and powerful would be get a method or a class for this api.

url to http api 
http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v3_3_4/priv/www/api/index.html 

Could You add it in qamqp ?

**Comment by mbroadst** [comment]
while rabbitmq is what this library was initially developed to communicate with, the qamqp project itself aims to be a broker-agnostic AMQP 0-9-1 library - so I think it's out of scope to build in support for rabbitmq's json api. The resource you pointed to looks like it could easily be wrapped using QNetworkAccessManager + the QJson classes, should not be too hard to implement but imho it's not this library's job
