### ISSUE TITLE
Message rejecting doesn't work

### ISSUE THREAD

**Issue by IgorSysoyev** [mbroadst/qamqp#67]
Hi,
I have a problem with message rejecting.
The following method 
`void QAmqpQueue::reject(const QAmqpMessage &message, bool requeue) ` 
doesn't work due to calling inside it wrong method. 
Current source code is:
```
void QAmqpQueue::reject(const QAmqpMessage &message, bool requeue)
{
    ack(message.deliveryTag(), requeue);
}
```
Have to be:
```
void QAmqpQueue::reject(const QAmqpMessage &message, bool requeue)
{
    reject(message.deliveryTag(), requeue);
}
```
Method
`void QAmqpQueue::reject(qlonglong deliveryTag, bool requeue) ` nevertheless works fine.

Thanks,
Igor

**Comment by mbroadst** [comment]
@IgorSysoyev thanks for pointing this out, contributions are most welcome!

**Comment by IgorSysoyev** [comment]
Fixed.
