### ISSUE TITLE
Qt 6 support

### ISSUE THREAD

**Issue by DmitryDemidov80** [mbroadst/qamqp#81]
Hi!
Will be Qt 6 support?
Now it has compile errors.

Needs
#include QIODevice
and problem with QHash::unite()

Thanks!

**Comment by AntonOrnatskyi** [comment]
And QSslSocket::error signal was obsolete

**Comment by droidsyer** [comment]
Some days ago, I made porting on Qt6. It was easy and fast. As soon as possible I should make a pull request. But I didn't tried to compile with Qt4.

**Comment by moruoxian** [comment]
> 
you can add this in your main
 qRegisterMetaType<QAbstractSocket::SocketState>();

**Comment by WollZebra** [comment]
Hi, I tried a port for Qt6.5. It is not a real problem. @mbroadst shall I open a branch + pull request here? 
If not I will fork it.
Qt4 support I would drop then. Qt themself did it long ago.

**Comment by mbroadst** [comment]
Hi @WollZebra, sure please do that. I haven't been using this library for some time, so I'm also interested in discussing sharing the maintenance with more actively-involved community members. Let me know if you're interested

**Comment by mbroadst** [comment]
@WollZebra let's work through a pull request together first, before discussing maintaining the project 😄 . Can you submit a pull request from your fork?

**Comment by WollZebra** [comment]
@mbroadst it would be really nice if you could review my PR.
We are already on the next challenge, to use it with Qt for WebAssemby. Key problem here is the use of it as external lib.
