### ISSUE TITLE
what is the qamqpd lib file? The document coming soon!

### ISSUE THREAD

**Issue by Tsingkai** [mbroadst/qamqp#82]
### Environment
---
+ Qt-Version: 5.12.8
+ OS: Ubuntu 20.04LTS

### Problem
---
Follow these steps:
1. Step 1：``` git clone https://github.com/mbroadst/qamqp.git```
2. Step 2:  open qamqp.pro by Qt Creator
3. Step 3:  compile the **src** project
4. Step 4:  compile the **hello world** project
5. these Errors
```
can not find -lqamqpd
collect2: error: ld returned 1 exit status
```

**So, where is the qamqpd lib file? **

### At Last
+ if the repo is archived，please the world shutdown now

**Comment by moruoxian** [comment]
the lib in this path  qamqp\src.

you can rename libqamqp.so  to libqamqpd.so ,because you uesed the Debug lib.
